services:
  claude-code:
    image: "ghcr.io/mfisher87/claude-code:${CLAUDE_CODE_VERSION:?Error: CLAUDE_CODE_VERSION is required}"
    build:
      context: "."
      args:
        CLAUDE_CODE_VERSION: "${CLAUDE_CODE_VERSION}"
